POST http://127.0.0.1:3333/register HTTP/1.1
content-type: application/json

{
  "firstname": "mehdi",
  "lastname": "gueta",
  "mail": "jiji@gma.com",
  "password": "123456"
}

###

POST  http://127.0.0.1:3333 HTTP/1.1
content-type: application/json

{
  "mail": "wawa@gma.com",
  "password": "123456"
}

###
GET http://127.0.0.1:3333/members/all HTTP/1.1
###
GET http://127.0.0.1:3333/logout HTTP/1.1
###
GET http://127.0.0.1:3333/projects/all HTTP/1.1

